# Generated by Django 2.0.8 on 2018-08-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Finalizado'), (2, 'Não finalizado')])),
                ('errors', models.IntegerField(default=0, verbose_name='erros')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UUIDUser2', to='hang.UUIDUser')),
            ],
            options={
                'verbose_name': 'partida',
                'verbose_name_plural': 'partidas',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=15, verbose_name='palavra')),
                ('clue', models.CharField(max_length=150, verbose_name='dica')),
            ],
            options={
                'verbose_name': 'palavra',
                'verbose_name_plural': 'palavras',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Word', to='hang.Word'),
        ),
    ]
